# GitHub Actions workflow untuk build Android (menghasilkan APK debug)
# - Trigger: push & pull_request
# - Menggunakan JDK 11 dan meng-install Android commandline tools (sdkmanager)
# - Mencache folder Gradle agar build lebih cepat
# - Men-generate assembleDebug dan meng-upload APK sebagai artifact
#
# Sesuaikan API level / build-tools / java version jika project Anda memakai versi lain.
name: Android CI - Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /opt/android-sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install prerequisites
        run: sudo apt-get update && sudo apt-get install -y unzip wget

      - name: Install Android command-line tools and SDK platforms
        run: |
          mkdir -p "$ANDROID_SDK_ROOT"
          cd /tmp
          # Download commandline tools (versi dapat diperbarui jika perlu)
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline.zip
          unzip -q cmdline.zip -d "$ANDROID_SDK_ROOT/cmdline-tools"
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          # Beberapa zip mengekstrak ke folder "cmdline-tools", pindahkan isinya ke 'latest'
          mv "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools/"* "$ANDROID_SDK_ROOT/cmdline-tools/latest/" || true
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"
          export PATH="$ANDROID_SDK_ROOT/platform-tools:$PATH"
          # Install basic packages (sesuaikan API / build-tools jika diperlukan)
          yes | sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" --licenses
          sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" "platform-tools" "platforms;android-33" "build-tools;33.0.2"
        shell: bash

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon --stacktrace
        # Jika ingin build release, gunakan: ./gradlew assembleRelease
        # Perhatian: release signing memerlukan keystore & secrets; contoh ada di penjelasan di bawah.

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/**/*.apk
