name: Android CI - Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # 🔥 Ini kuncinya bro — Gradle dijalankan dari folder KASIR/
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: KASIR

      - name: Build APK
        run: ./gradlew assembleDebug
        working-directory: KASIR

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: KASIR/app/build/outputs/apk/debug/app-debug.apk
